In [2]:
import pandas as pd

data = {
    "Nama" : ["A", "B", "C", "D"],
    "Kelas" : [2, 3, 4, 5],
    "Nilai" : [80, 85, 90, 95]

}

In [5]:
print(data)

{'Nama': ['A', 'B', 'C', 'D'], 'Kelas': [2, 3, 4, 5], 'Nilai': [80, 85, 90, 95]}

In [6]:
df = pd.DataFrame(data)
df

  Nama  Kelas  Nilai
0    A      2     80
1    B      3     85
2    C      4     90
3    D      5     95

In [10]:
print('Menampilkan head \n')
df.head()

Menampilkan head

  Nama  Kelas  Nilai
0    A      2     80
1    B      3     85
2    C      4     90
3    D      5     95

In [11]:
print('Menampilkan describe \n')
df.describe()

Menampilkan describe

          Kelas      Nilai
count  4.000000   4.000000
mean   3.500000  87.500000
std    1.290994   6.454972
min    2.000000  80.000000
25%    2.750000  83.750000
50%    3.500000  87.500000
75%    4.250000  91.250000
max    5.000000  95.000000

In [12]:
print('Menampilkan info \n')
df.info()

Menampilkan info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nama    4 non-null      object
 1   Kelas   4 non-null      int64
 2   Nilai   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes

In [ ]:
print(df.loc[0, "Nama"])
print(df.iloc[1, 1])